import SwiftUI

struct TicketSetupView: View {
    // MARK: - Constants
    private static let dateFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateFormat = "dd/MM/yyyy"
        return formatter
    }()
    
    private static let dayFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "tr_TR")
        formatter.dateFormat = "d MMMM EEEE"
        return formatter
    }()

    fileprivate struct PresetCouponResult {
        let dayIndex: Int
        let budget: Int
        let city: String
        let betLabel: String
        let actualCost: Double
        let legs: [[String]]              // horse numbers per leg (display)
        let selections: [String: Set<String>]  // raceKOD → horseKODs (for TicketView)
        let raceDay: BetRaceDay
        let betType: BetType
    }

    @State private var navigateToTicket = false
    @State private var showAISettings = false
    @State private var isLoadingData = false
    @State private var presetCity1: String? = nil
    @State private var presetCity2: String? = nil
    @State private var presetResults: [String: PresetCouponResult] = [:]
    // AI Ayarları
    @State private var raceDays: [BetRaceDay] = []
    @State private var selectedDayIndex: Int = 0
    @State private var selectedBetIndex: Int = 0
    @State private var budget: String = "500"
    @State private var autoGeneratedHorses: [String: Set<String>]? = nil
    
    @FocusState private var isBudgetFocused: Bool
    
    let themePrimary = Color.cyan
    let themeAccent = Color.orange

    // Safe access computed properties
    private var selectedDay: BetRaceDay? {
        guard !raceDays.isEmpty, selectedDayIndex < raceDays.count else { return nil }
        return raceDays[selectedDayIndex]
    }
    
    private var currentGanyanTypes: [BetType] {
        getGanyanTypes(for: selectedDay)
    }
    
    private var selectedBet: BetType? {
        let available = currentGanyanTypes
        guard !available.isEmpty, selectedBetIndex < available.count else { return nil }
        return available[selectedBetIndex]
    }

    var body: some View {
        NavigationStack {
            ZStack {
                RadialGradient(colors: [Color(white: 0.15), .black], center: .center, startRadius: 2, endRadius: 700)
                    .ignoresSafeArea(.all)
                
                ScrollView(showsIndicators: false) {
                    VStack(spacing: 2) {

                        LogoHeaderView(themePrimary: themePrimary)
                            .padding(.top, 0)

                        if !showAISettings {
                            MainOptionsView(
                                themePrimary: themePrimary,
                                prepareAISelection: prepareAISelection,
                                createTicketManually: {
                                    autoGeneratedHorses = nil
                                    navigateToTicket = true
                                }
                            )
                            PresetCouponsView(
                                results: presetResults,
                                onSelect: { dayIndex, budget in presetGenerate(dayIndex: dayIndex, budgetAmount: budget) }
                            )
                                .padding(.top, 8)
                        } else {
                            AISettingsView(
                                raceDays: raceDays,
                                selectedDayIndex: $selectedDayIndex,
                                selectedBetIndex: $selectedBetIndex,
                                budget: $budget,
                                isBudgetFocused: $isBudgetFocused,
                                themePrimary: themePrimary,
                                themeAccent: themeAccent,
                                getGanyanTypes: getGanyanTypes,
                                betTypeLabelForAI: betTypeLabelForAI,
                                formattedRaceDayTitle: formattedRaceDayTitle,
                                onGenerate: generateAIKupon,
                                onBack: {
                                    isBudgetFocused = false
                                    withAnimation(.spring()) { showAISettings = false }
                                }
                            )
                            .transition(.move(edge: .trailing).combined(with: .opacity))
                        }
                    }
                    .padding(.bottom, 100)
                }
                .scrollDismissesKeyboard(.interactively)
                
                if isLoadingData {
                    ProcessingOverlay(text: "Analiz Ediliyor...", themePrimary: themePrimary)
                }
            }
            .navigationDestination(isPresented: $navigateToTicket) {
                let hasDays = !raceDays.isEmpty
                TicketView(
                    initialSelections: autoGeneratedHorses,
                    initialDay: hasDays ? selectedDay : nil,
                    initialBet: hasDays ? selectedBet : nil,
                    initialDays: hasDays ? raceDays : nil
                )
            }
            .onChange(of: selectedDayIndex) { _, _ in
                updateSelectedBetForCurrentDay()
            }
            .onChange(of: navigateToTicket) { _, isNavigating in
                if !isNavigating && showAISettings { resetAIState() }
            }
            .task { await loadPresetCities() }
        }

    }
    
    // MARK: - Logic Helpers
    
    private func updateSelectedBetForCurrentDay() {
        let ganyans = currentGanyanTypes
        let priorities = ["6'lı", "5'li", "4'lü", "3'lü"]
        for p in priorities {
            // Prefer 2nd (last) within same category, otherwise 1st
            let matching = ganyans.indices.filter { ganyans[$0].BAHIS.contains(p) }
            if let lastIdx = matching.last {
                selectedBetIndex = lastIdx
                return
            }
        }
        selectedBetIndex = 0
    }
    
    private func resetAIState() {
        withAnimation(.spring()) { showAISettings = false }
        selectedDayIndex = 0
        updateSelectedBetForCurrentDay()
        budget = "500"
        autoGeneratedHorses = nil
    }

    private func prepareAISelection() {
        isLoadingData = true
        Task {
            do {
                let decoded = try await JsonParser().getBetData()
                let filtered = decoded.data.yarislar.filter { (Int($0.KOD) ?? 99) < 11 }
                
                await MainActor.run {
                    self.raceDays = filtered
                    self.selectedDayIndex = 0
                    updateSelectedBetForCurrentDay()
                    self.isLoadingData = false
                    DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
                        withAnimation(.spring(response: 0.4, dampingFraction: 0.8)) {
                            self.showAISettings = true
                        }
                    }
                }
            } catch {
                await MainActor.run { self.isLoadingData = false }
            }
        }
    }
    
    private func generateAIKupon() {
        guard let day = selectedDay, let bet = selectedBet, let maxBudget = Double(budget) else { return }
        isBudgetFocused = false
        isLoadingData = true
        
        Task.detached(priority: .userInitiated) {
            let races = await filteredRacesForAI(for: day, betType: bet)
            let unitPrice = Double(bet.POOLUNIT) / 100.0
            let result = TicketSetupView.computeAISelections(races: races, maxBudget: maxBudget, unitPrice: unitPrice)
            await MainActor.run {
                self.autoGeneratedHorses = result
                self.isLoadingData = false
                self.navigateToTicket = true
            }
        }
    }

    private func getGanyanTypes(for day: BetRaceDay?) -> [BetType] {
        guard let day = day else { return [] }
        let allowed = ["6'lı Ganyan", "5'li Ganyan", "4'lü Ganyan", "3'lü Ganyan"]
        return day.bahisler
            .filter { type in allowed.contains { type.BAHIS.localizedCaseInsensitiveContains($0) } }
            .flatMap { $0.expanded() }
    }
    
    private func betTypeLabelForAI(for type: BetType, list: [BetType]) -> String {
        let sameGroup = list.filter { $0.BAHIS == type.BAHIS }
        if sameGroup.count > 1, let index = sameGroup.firstIndex(where: { $0.id == type.id }) {
            return "\(index + 1). \(type.BAHIS.uppercased())"
        }
        return type.BAHIS.uppercased()
    }
    
    private func formattedRaceDayTitle(for day: BetRaceDay?) -> String {
        guard let day = day else { return "Seçiniz" }
        let yer = day.YER.turkishCityUppercased
        if let date = Self.dateFormatter.date(from: day.TARIH) {
            return "\(yer) - \(Self.dayFormatter.string(from: date).uppercased(with: Locale(identifier: "tr_TR")))"
        }
        return yer
    }

    private func loadPresetCities() async {
        guard presetCity1 == nil else { return }
        do {
            let decoded = try await JsonParser().getBetData()
            let filtered = decoded.data.yarislar.filter { (Int($0.KOD) ?? 99) < 11 }
            let daysWithSixli = filtered.filter { getGanyanTypes(for: $0).contains { $0.BAHIS.contains("6'lı") } }
            presetCity1 = daysWithSixli.first?.YER.turkishCityUppercased
            presetCity2 = daysWithSixli.dropFirst().first?.YER.turkishCityUppercased

            for (dayIndex, raceDay) in daysWithSixli.prefix(2).enumerated() {
                let ganyans = getGanyanTypes(for: raceDay)
                let sixliList = ganyans.filter { $0.BAHIS.contains("6'lı") }
                guard let bet = sixliList.count >= 2 ? sixliList[1] : sixliList.first ?? ganyans.first else { continue }
                let betLabel = betTypeLabelForAI(for: bet, list: ganyans)
                let city = raceDay.YER.turkishCityUppercased
                let races = filteredRacesForAI(for: raceDay, betType: bet)
                let unitPrice = Double(bet.POOLUNIT) / 100.0

                for budget in [500, 1000] {
                    let maxBudget = Double(budget)
                    let key = "\(dayIndex)_\(budget)"
                    Task.detached(priority: .utility) {
                        let selections = TicketSetupView.computeAISelections(
                            races: races, maxBudget: maxBudget, unitPrice: unitPrice
                        )
                        let actualCost = races.reduce(1.0) {
                            $0 * Double(max(selections[$1.KOD]?.count ?? 0, 1))
                        } * unitPrice
                        let legs: [[String]] = races.map { race in
                            let selectedKods = selections[race.KOD] ?? []
                            return race.atlar?
                                .filter { selectedKods.contains($0.KOD) }
                                .compactMap { Int($0.NO) }
                                .sorted()
                                .map { String($0) } ?? []
                        }
                        await MainActor.run {
                            self.presetResults[key] = PresetCouponResult(
                                dayIndex: dayIndex, budget: budget,
                                city: city, betLabel: betLabel,
                                actualCost: actualCost, legs: legs,
                                selections: selections,
                                raceDay: raceDay, betType: bet
                            )
                        }
                    }
                }
            }
        } catch {}
    }

    private func presetGenerate(dayIndex: Int, budgetAmount: Int) {
        let key = "\(dayIndex)_\(budgetAmount)"

        // If already computed, use cached selections directly
        if let cached = presetResults[key] {
            isLoadingData = true
            Task {
                do {
                    let decoded = try await JsonParser().getBetData()
                    let filtered = decoded.data.yarislar.filter { (Int($0.KOD) ?? 99) < 11 }
                    let matchingDay = filtered.first { $0.id == cached.raceDay.id } ?? cached.raceDay
                    let ganyans = getGanyanTypes(for: matchingDay)
                    let allDayIdx = filtered.firstIndex(where: { $0.id == matchingDay.id }) ?? 0
                    let betIdx = ganyans.firstIndex(where: { $0.id == cached.betType.id }) ?? 0
                    await MainActor.run {
                        self.raceDays = filtered
                        self.selectedDayIndex = allDayIdx
                        self.selectedBetIndex = betIdx
                        self.budget = "\(budgetAmount)"
                        self.autoGeneratedHorses = cached.selections
                        self.isLoadingData = false
                        self.navigateToTicket = true
                    }
                } catch {
                    await MainActor.run { isLoadingData = false }
                }
            }
            return
        }

        // Fallback: generate fresh
        isLoadingData = true
        Task {
            do {
                let decoded = try await JsonParser().getBetData()
                let filtered = decoded.data.yarislar.filter { (Int($0.KOD) ?? 99) < 11 }
                let daysWithSixli = filtered.filter { getGanyanTypes(for: $0).contains { $0.BAHIS.contains("6'lı") } }

                guard dayIndex < daysWithSixli.count else {
                    await MainActor.run { isLoadingData = false }
                    return
                }

                let raceDay = daysWithSixli[dayIndex]
                let ganyans = getGanyanTypes(for: raceDay)
                let sixliList = ganyans.filter { $0.BAHIS.contains("6'lı") }
                let targetBet = sixliList.count >= 2 ? sixliList[1] : sixliList.first ?? ganyans.first

                guard let bet = targetBet else {
                    await MainActor.run { isLoadingData = false }
                    return
                }

                let allDayIdx = filtered.firstIndex(where: { $0.id == raceDay.id }) ?? 0
                let betIdx = ganyans.firstIndex(where: { $0.id == bet.id }) ?? 0

                await MainActor.run {
                    self.raceDays = filtered
                    self.selectedDayIndex = allDayIdx
                    self.selectedBetIndex = betIdx
                    self.budget = "\(budgetAmount)"
                    self.autoGeneratedHorses = nil
                    self.isLoadingData = false
                    self.generateAIKupon()
                }
            } catch {
                await MainActor.run { isLoadingData = false }
            }
        }
    }

    private static func computeAISelections(
        races: [BetRace], maxBudget: Double, unitPrice: Double
    ) -> [String: Set<String>] {
        var bestSelections: [String: Set<String>] = [:]
        var bestPriceFound = 0.0
        for _ in 0..<10 {
            var currentSelections: [String: Set<String>] = [:]
            for r in races {
                let fav = r.atlar?.filter({ $0.KOSMAZ != true })
                    .sorted(by: { ($0.AGF1 ?? 0) > ($1.AGF1 ?? 0) }).first
                currentSelections[r.KOD] = fav != nil ? [fav!.KOD] : []
            }
            var canImprove = true
            while canImprove {
                canImprove = false
                var validMoves: [(raceKod: String, horseKod: String, nextPrice: Double)] = []
                let currentCombos: Double = races.reduce(1.0) { acc, r in
                    let cnt = currentSelections[r.KOD]?.count ?? 0
                    return acc * Double(max(cnt, 1))
                }
                for r in races {
                    let selectedInRace = currentSelections[r.KOD] ?? []
                    let available = r.atlar?.filter { h in h.KOSMAZ != true && !selectedInRace.contains(h.KOD) }
                        .sorted(by: { ($0.AGF1 ?? 0) > ($1.AGF1 ?? 0) }) ?? []
                    if let nextHorse = available.first {
                        let count = Double(max(selectedInRace.count, 1))
                        let nextPrice = (currentCombos / count) * (count + 1) * unitPrice
                        if nextPrice <= maxBudget { validMoves.append((r.KOD, nextHorse.KOD, nextPrice)) }
                    }
                }
                if let move = validMoves.randomElement() {
                    currentSelections[move.raceKod]?.insert(move.horseKod)
                    canImprove = true
                }
            }
            let finalPrice = races.reduce(1.0) { $0 * Double(max(currentSelections[$1.KOD]?.count ?? 0, 1)) } * unitPrice
            if finalPrice > bestPriceFound { bestPriceFound = finalPrice; bestSelections = currentSelections }
        }
        return bestSelections
    }

    private func filteredRacesForAI(for raceDay: BetRaceDay, betType: BetType) -> [BetRace] {
        let startRaceNo = betType.kosular.first ?? 1
        let name = betType.BAHIS.lowercased()
        let legCountMap: [String: Int] = ["7'li": 7, "6'lı": 6, "5'li": 5, "4'lü": 4, "3'lü": 3]
        let legCount = legCountMap.first(where: { name.contains($0.key) })?.value ?? 1
        
        let sortedRaces = (raceDay.kosular ?? []).sorted { (Int($0.NO) ?? 0) < (Int($1.NO) ?? 0) }
        if let startIndex = sortedRaces.firstIndex(where: { Int($0.NO) == startRaceNo }) {
            return Array(sortedRaces[startIndex..<min(startIndex + legCount, sortedRaces.count)])
        }
        return []
    }
}

// MARK: - View Components
private extension TicketSetupView {
    
    struct LogoHeaderView: View {
        let themePrimary: Color
        private let logoSize: CGFloat = 100
        
        var body: some View {
            ZStack {
                Circle()
                    .fill(themePrimary.opacity(0.1))
                    .frame(width: logoSize, height: logoSize)
                Circle()
                    .stroke(LinearGradient(colors: [themePrimary, .clear], startPoint: .topLeading, endPoint: .bottomTrailing), lineWidth: 3)
                    .frame(width: logoSize + 10, height: logoSize + 10)
                Image("tayzekatransparent")
                    .resizable()
                    .scaledToFit()
                    .frame(width: logoSize + 60, height: logoSize + 60)
                    .clipShape(Circle())
            }
        }
    }
    
    struct MainOptionsView: View {
        let themePrimary: Color
        let prepareAISelection: () -> Void
        let createTicketManually: () -> Void

        var body: some View {
            VStack(spacing: 20) {
                raceCard(
                    image: "tayzekacoupon",
                    title: "TAYZEKA HAZIRLASIN",
                    action: prepareAISelection
                )
                raceCard(
                    image: "customcoupon",
                    title: "KENDİM OLUŞTURACAĞIM",
                    action: createTicketManually
                )
            }
            .padding(.horizontal, 16)
        }

        private func raceCard(image: String, title: String, action: @escaping () -> Void) -> some View {
            Button(action: action) {
                ZStack {
                    Image(image)
                        .resizable()
                        .aspectRatio(contentMode: .fill)
                        .frame(maxWidth: .infinity, maxHeight: .infinity)
                        .clipped()

                    LinearGradient(
                        gradient: Gradient(colors: [
                            Color.black.opacity(0.85),
                            Color.black.opacity(0.4),
                            Color.clear
                        ]),
                        startPoint: .leading,
                        endPoint: .trailing
                    )

                    HStack {
                        Text(title)
                            .font(.system(size: 20, weight: .black, design: .rounded))
                            .tracking(1)
                            .foregroundColor(.white)
                        Spacer()
                    }
                    .padding(.horizontal, 25)
                }
                .frame(height: 110)
                .frame(maxWidth: .infinity)
                .background(Color.gray.opacity(0.2))
                .cornerRadius(20)
                .overlay(
                    RoundedRectangle(cornerRadius: 20)
                        .stroke(Color.white.opacity(0.15), lineWidth: 1)
                )
                .shadow(color: .black.opacity(0.4), radius: 10, x: 0, y: 6)
            }
            .buttonStyle(CardPressEffectStyle())
        }
    }
    
    struct AISettingsView: View {
        let raceDays: [BetRaceDay]
        @Binding var selectedDayIndex: Int
        @Binding var selectedBetIndex: Int
        @Binding var budget: String
        @FocusState.Binding var isBudgetFocused: Bool
        
        let themePrimary: Color
        let themeAccent: Color
        let getGanyanTypes: (BetRaceDay?) -> [BetType]
        let betTypeLabelForAI: (BetType, [BetType]) -> String
        let formattedRaceDayTitle: (BetRaceDay?) -> String
        let onGenerate: () -> Void
        let onBack: () -> Void

        var body: some View {
            let currentDay = selectedDayIndex < raceDays.count ? raceDays[selectedDayIndex] : nil
            let available = getGanyanTypes(currentDay)
            let currentBet = selectedBetIndex < available.count ? available[selectedBetIndex] : nil

            VStack(spacing: 0) {
                Menu {
                    Picker("", selection: $selectedDayIndex) {
                        ForEach(0..<raceDays.count, id: \.self) { i in
                            Text(formattedRaceDayTitle(raceDays[i])).tag(i)
                        }
                    }
                } label: {
                    menuRow(
                        icon: "mappin.and.ellipse",
                        label: "HİPODROM",
                        value: formattedRaceDayTitle(currentDay),
                        accentColor: themePrimary
                    )
                }

                rowDivider

                // Bahis türü satırı
                Menu {
                    Picker("", selection: $selectedBetIndex) {
                        ForEach(0..<available.count, id: \.self) { i in
                            Text(betTypeLabelForAI(available[i], available)).tag(i)
                        }
                    }
                } label: {
                    menuRow(
                        icon: "ticket.fill",
                        label: "BAHİS TÜRÜ",
                        value: currentBet.map { betTypeLabelForAI($0, available) } ?? "Seçiniz",
                        accentColor: themePrimary
                    )
                }

                rowDivider

                VStack(alignment: .leading, spacing: 12) {
                    HStack(spacing: 6) {
                        Text("BÜTÇE")
                            .font(.system(size: 11, weight: .black))
                            .foregroundColor(themePrimary)
                    }

                    HStack(alignment: .center, spacing: 4) {
                        Text("₺")
                            .font(.system(size: 28, weight: .bold))
                            .foregroundColor(themeAccent)
                        TextField("500", text: $budget)
                            .keyboardType(.decimalPad)
                            .font(.system(size: 28, weight: .heavy, design: .rounded))
                            .foregroundColor(themeAccent)
                            .focused($isBudgetFocused)
                        Spacer()
                        Button(action: onGenerate) {
                            HStack(spacing: 6) {
                                Image(systemName: "sparkles")
                                    .font(.system(size: 12, weight: .bold))
                                Text("HAZIRLA")
                                    .font(.system(size: 13, weight: .heavy))
                                    .tracking(1.5)
                            }
                            .foregroundColor(.black)
                            .padding(.horizontal, 16)
                            .padding(.vertical, 10)
                            .background(
                                LinearGradient(
                                    colors: [themePrimary, themePrimary.opacity(0.75)],
                                    startPoint: .leading,
                                    endPoint: .trailing
                                )
                            )
                            .cornerRadius(12)
                            .shadow(color: themePrimary.opacity(0.45), radius: 10, x: 0, y: 4)
                        }
                    }
                }
                .padding(.horizontal, 18)
                .padding(.vertical, 16)

                HStack {
                    Spacer()
                    Button(action: onBack) {
                        Text("Vazgeç")
                            .font(.system(size: 13, weight: .medium))
                            .foregroundColor(.white.opacity(0.35))
                    }
                    Spacer()
                }
                .padding(.vertical, 12)
            }
            .background(Color(white: 0.1))
            .cornerRadius(18)
            .overlay(
                RoundedRectangle(cornerRadius: 18)
                    .stroke(Color.white.opacity(0.08), lineWidth: 1)
            )
            .padding(.horizontal, 20)
        }

        private var rowDivider: some View {
            Rectangle()
                .fill(Color.white.opacity(0.07))
                .frame(height: 1)
                .padding(.horizontal, 14)
        }

        private func menuRow(icon: String, label: String, value: String, accentColor: Color) -> some View {
            HStack(spacing: 14) {
                Image(systemName: icon)
                    .font(.system(size: 15, weight: .semibold))
                    .foregroundColor(accentColor)
                    .frame(width: 22)

                VStack(alignment: .leading, spacing: 3) {
                    Text(label)
                        .font(.system(size: 10, weight: .black))
                        .foregroundColor(accentColor.opacity(0.8))
                    Text(value)
                        .font(.system(size: 15, weight: .bold))
                        .foregroundColor(.white)
                        .lineLimit(1)
                }

                Spacer()

                Image(systemName: "chevron.up.chevron.down")
                    .font(.system(size: 11, weight: .medium))
                    .foregroundColor(.white.opacity(0.25))
            }
            .padding(.horizontal, 18)
            .padding(.vertical, 15)
            .contentShape(Rectangle())
        }
    }
    
    struct PresetCouponsView: View {
        private let results: [String: PresetCouponResult]
        let onSelect: (Int, Int) -> Void
        
        init(results: [String: PresetCouponResult], onSelect: @escaping (Int, Int) -> Void) {
            self.results = results
            self.onSelect = onSelect
        }

        private struct CardItem: Identifiable {
            let id = UUID()
            let dayIndex: Int
            let budget: Int
        }
        private let items: [CardItem] = [
            CardItem(dayIndex: 0, budget: 500),
            CardItem(dayIndex: 0, budget: 1000),
            CardItem(dayIndex: 1, budget: 500),
            CardItem(dayIndex: 1, budget: 1000),
        ]

        private func formatCost(_ amount: Double) -> String {
            let val = Int(amount)
            if val >= 1000 { return "₺\(val / 1000).\(String(format: "%03d", val % 1000))" }
            return "₺\(val)"
        }

        var body: some View {
            VStack(alignment: .leading, spacing: 12) {
                HStack(spacing: 6) {
                    Image(systemName: "sparkles")
                        .font(.system(size: 10, weight: .bold))
                        .foregroundColor(.cyan)
                    Text("TAYZEKA HAZIR KUPONLARI")
                        .font(.system(size: 10, weight: .black))
                        .foregroundColor(.white.opacity(0.4))
                        .tracking(1.2)
                }
                .padding(.horizontal, 4)

                VStack(spacing: 10) {
                    ForEach(items) { item in
                        let key = "\(item.dayIndex)_\(item.budget)"
                        Button { onSelect(item.dayIndex, item.budget) } label: {
                            couponCard(result: results[key], budget: item.budget)
                        }
                        .buttonStyle(CardPressEffectStyle())
                    }
                }
            }
            .padding(.horizontal, 16)
        }

        private func couponCard(result: PresetCouponResult?, budget: Int) -> some View {
            let paper  = Color(red: 0.96, green: 0.91, blue: 0.79)
            let ink    = Color(red: 0.10, green: 0.50, blue: 0.54)
            let inkDim = ink.opacity(0.55)

            return ZStack {
                // Aged paper base
                RoundedRectangle(cornerRadius: 5)
                    .fill(paper)
                // Slight worn gradient overlay
                RoundedRectangle(cornerRadius: 5)
                    .fill(LinearGradient(
                        colors: [Color.brown.opacity(0.06), Color.clear, Color.brown.opacity(0.04)],
                        startPoint: .topLeading, endPoint: .bottomTrailing
                    ))
                // Border
                RoundedRectangle(cornerRadius: 5)
                    .stroke(ink.opacity(0.7), lineWidth: 1.5)

                if let result {
                    VStack(spacing: 0) {

                        // ── HEADER ──────────────────────────────────────────
                        HStack(alignment: .center, spacing: 8) {
                            // "6" badge (like the "A" box in original)
                            Text("6")
                                .font(.system(size: 15, weight: .black, design: .serif))
                                .foregroundColor(ink)
                                .frame(width: 22, height: 22)
                                .overlay(Rectangle().stroke(ink, lineWidth: 1.5))

                            VStack(alignment: .leading, spacing: 1) {
                                Text("TÜRKİYE JOKEY KULÜBÜ")
                                    .font(.system(size: 7, weight: .bold, design: .monospaced))
                                    .foregroundColor(ink)
                                Text(result.betLabel + " BİLETİ")
                                    .font(.system(size: 7.5, weight: .bold, design: .monospaced))
                                    .foregroundColor(ink)
                            }
                            Spacer()
                        }
                        .padding(.horizontal, 10)
                        .padding(.vertical, 6)

                        Rectangle().fill(inkDim).frame(height: 0.75)

                        // ── META ROW ────────────────────────────────────────
                        HStack(spacing: 0) {
                            Text("HİPODROM: \(result.city)")
                                .font(.system(size: 7, weight: .medium, design: .monospaced))
                                .foregroundColor(ink)
                            Spacer()
                            Text("TAYZEKA SEÇİMİ")
                                .font(.system(size: 6.5, weight: .regular, design: .monospaced))
                                .foregroundColor(inkDim)
                        }
                        .padding(.horizontal, 10)
                        .padding(.vertical, 4)

                        Rectangle().fill(inkDim).frame(height: 0.75)

                        // ── 6 COLUMNS ───────────────────────────────────────
                        HStack(alignment: .top, spacing: 0) {
                            ForEach(Array(result.legs.enumerated()), id: \.offset) { legIdx, horses in
                                if legIdx > 0 {
                                    Rectangle().fill(inkDim).frame(width: 0.75)
                                }
                                VStack(spacing: 0) {
                                    // Column header
                                    Text("G.\(legIdx + 1)")
                                        .font(.system(size: 8, weight: .bold, design: .monospaced))
                                        .foregroundColor(ink)
                                        .frame(maxWidth: .infinity)
                                        .padding(.vertical, 3)
                                        .background(ink.opacity(0.12))

                                    Rectangle().fill(inkDim).frame(height: 0.75)

                                    // Selected horse numbers — filled teal boxes
                                    VStack(spacing: 2) {
                                        ForEach(horses, id: \.self) { no in
                                            Text(no)
                                                .font(.system(size: 12, weight: .black, design: .monospaced))
                                                .foregroundColor(paper)
                                                .frame(maxWidth: .infinity)
                                                .frame(height: 19)
                                                .background(ink.opacity(0.88))
                                        }
                                    }
                                    .padding(.vertical, 5)
                                    .padding(.horizontal, 2)
                                    .frame(maxWidth: .infinity, minHeight: 36, alignment: .top)
                                }
                                .frame(maxWidth: .infinity)
                            }
                        }
                        .padding(.horizontal, 6)
                        .overlay(
                            Rectangle()
                                .stroke(inkDim, lineWidth: 0.75)
                                .padding(.horizontal, 6)
                        )

                        Rectangle().fill(inkDim).frame(height: 0.75)

                        // ── FOOTER ──────────────────────────────────────────
                        HStack {
                            let combos = result.legs.reduce(1) { $0 * max($1.count, 1) }
                            Text("\(combos) kombinasyon")
                                .font(.system(size: 7, weight: .regular, design: .monospaced))
                                .foregroundColor(inkDim)
                            Spacer()
                            Text(formatCost(result.actualCost))
                                .font(.system(size: 14, weight: .black, design: .monospaced))
                                .foregroundColor(Color(red: 0.85, green: 0.35, blue: 0.1))
                            Text("TL")
                                .font(.system(size: 8, weight: .bold, design: .monospaced))
                                .foregroundColor(ink)
                        }
                        .padding(.horizontal, 10)
                        .padding(.vertical, 5)
                    }
                } else {
                    HStack(spacing: 8) {
                        ProgressView().scaleEffect(0.65).tint(ink)
                        Text("Kupon hazırlanıyor...")
                            .font(.system(size: 10, weight: .medium, design: .monospaced))
                            .foregroundColor(inkDim)
                    }
                    .padding(16)
                    .frame(maxWidth: .infinity, alignment: .leading)
                }
            }
            .frame(maxWidth: .infinity)
            .shadow(color: .black.opacity(0.25), radius: 5, x: 2, y: 3)
        }
    }

    struct ProcessingOverlay: View {
        let text: String
        let themePrimary: Color
        @State private var isAnimating = false
        
        var body: some View {
            ZStack {
                Color.black.opacity(0.85).ignoresSafeArea()
                VStack(spacing: 25) {
                    Circle()
                        .trim(from: 0, to: 0.7)
                        .stroke(themePrimary, lineWidth: 4)
                        .frame(width: 50, height: 50)
                        .rotationEffect(.degrees(isAnimating ? 360 : 0))
                    Text(text).font(.headline).foregroundColor(.white)
                }
            }
            .onAppear {
                withAnimation(.linear(duration: 1).repeatForever(autoreverses: false)) { isAnimating = true }
            }
        }
    }
}

#Preview {
    TicketSetupView()
        .preferredColorScheme(.dark)
}

