import SwiftUI

struct TicketSetupView: View {
    // MARK: - Constants
    private static let dateFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateFormat = "dd/MM/yyyy"
        return formatter
    }()
    
    private static let dayFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "tr_TR")
        formatter.dateFormat = "EEEE"
        return formatter
    }()

    @State private var navigateToTicket = false
    @State private var showAISettings = false
    @State private var isLoadingData = false
    // AI Ayarları
    @State private var raceDays: [BetRaceDay] = []
    @State private var selectedDayIndex: Int = 0
    @State private var selectedBetIndex: Int = 0
    @State private var budget: String = "500"
    @State private var autoGeneratedHorses: [String: Set<String>]? = nil
    
    @FocusState private var isBudgetFocused: Bool
    
    let themePrimary = Color.cyan
    let themeAccent = Color.orange
    let quickBudgets = ["100", "250", "500", "1000","2500"]

    // Safe access computed properties
    private var selectedDay: BetRaceDay? {
        guard !raceDays.isEmpty, selectedDayIndex < raceDays.count else { return nil }
        return raceDays[selectedDayIndex]
    }
    
    private var currentGanyanTypes: [BetType] {
        getGanyanTypes(for: selectedDay)
    }
    
    private var selectedBet: BetType? {
        let available = currentGanyanTypes
        guard !available.isEmpty, selectedBetIndex < available.count else { return nil }
        return available[selectedBetIndex]
    }

    var body: some View {
        NavigationStack {
            ZStack {
                RadialGradient(colors: [Color(white: 0.15), .black], center: .center, startRadius: 2, endRadius: 700)
                    .ignoresSafeArea(.all)
                
                ScrollView(showsIndicators: false) {
                    VStack(spacing: 2) {

                        LogoHeaderView(themePrimary: themePrimary)
                            .padding(.top, 0)

                        if !showAISettings {
                            MainOptionsView(
                                themePrimary: themePrimary,
                                prepareAISelection: prepareAISelection,
                                createTicketManually: {
                                    autoGeneratedHorses = nil
                                    navigateToTicket = true
                                }
                            )
                        } else {
                            AISettingsView(
                                raceDays: raceDays,
                                selectedDayIndex: $selectedDayIndex,
                                selectedBetIndex: $selectedBetIndex,
                                budget: $budget,
                                isBudgetFocused: $isBudgetFocused,
                                themePrimary: themePrimary,
                                themeAccent: themeAccent,
                                quickBudgets: quickBudgets,
                                getGanyanTypes: getGanyanTypes,
                                betTypeLabelForAI: betTypeLabelForAI,
                                formattedRaceDayTitle: formattedRaceDayTitle,
                                onGenerate: generateAIKupon,
                                onBack: {
                                    isBudgetFocused = false
                                    withAnimation(.spring()) { showAISettings = false }
                                }
                            )
                            .transition(.move(edge: .trailing).combined(with: .opacity))
                        }
                    }
                    .padding(.bottom, 100)
                }
                .scrollDismissesKeyboard(.interactively)
                
                if isLoadingData {
                    ProcessingOverlay(text: "Analiz Ediliyor...", themePrimary: themePrimary)
                }
            }
            .navigationDestination(isPresented: $navigateToTicket) {
                TicketView(initialSelections: autoGeneratedHorses, initialDay: selectedDay, initialBet: selectedBet)
            }
            .onChange(of: selectedDayIndex) { _, _ in
                updateSelectedBetForCurrentDay()
            }
            .onChange(of: navigateToTicket) { _, isNavigating in
                if !isNavigating && showAISettings { resetAIState() }
            }
        }
        
    }
    
    // MARK: - Logic Helpers
    
    private func updateSelectedBetForCurrentDay() {
        let ganyans = currentGanyanTypes
        let priorities = ["6'lı", "5'li", "4'lü", "3'lü"]
        for p in priorities {
            if let index = ganyans.firstIndex(where: { $0.BAHIS.contains(p) }) {
                selectedBetIndex = index
                return
            }
        }
        selectedBetIndex = 0
    }
    
    private func resetAIState() {
        withAnimation(.spring()) { showAISettings = false }
        selectedDayIndex = 0
        updateSelectedBetForCurrentDay()
        budget = "500"
        autoGeneratedHorses = nil
    }

    private func prepareAISelection() {
        isLoadingData = true
        Task {
            do {
                let decoded = try await JsonParser().getBetData()
                let filtered = decoded.data.yarislar.filter { (Int($0.KOD) ?? 99) < 11 }
                
                await MainActor.run {
                    self.raceDays = filtered
                    self.selectedDayIndex = 0
                    updateSelectedBetForCurrentDay()
                    self.isLoadingData = false
                    DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
                        withAnimation(.spring(response: 0.4, dampingFraction: 0.8)) {
                            self.showAISettings = true
                        }
                    }
                }
            } catch {
                await MainActor.run { self.isLoadingData = false }
            }
        }
    }
    
    private func generateAIKupon() {
        guard let day = selectedDay, let bet = selectedBet, let maxBudget = Double(budget) else { return }
        isBudgetFocused = false
        isLoadingData = true
        
        Task.detached(priority: .userInitiated) {
            let races = await filteredRacesForAI(for: day, betType: bet)
            let unitPrice = Double(bet.POOLUNIT) / 100.0
            var bestSelections: [String: Set<String>] = [:]
            var bestPriceFound = 0.0
            
            for _ in 0..<10 {
                var currentSelections: [String: Set<String>] = [:]
                for r in races {
                    let fav = r.atlar?.filter({ $0.KOSMAZ != true }).sorted(by: { ($0.AGF1 ?? 0) > ($1.AGF1 ?? 0) }).first
                    currentSelections[r.KOD] = fav != nil ? [fav!.KOD] : []
                }
                
                var canImprove = true
                while canImprove {
                    canImprove = false
                    var validMoves: [(raceKod: String, horseKod: String, nextPrice: Double)] = []
                    let currentCombos = races.reduce(1.0) { $0 * Double(max(currentSelections[$1.KOD]?.count ?? 0, 1)) }
                    
                    for r in races {
                        let selectedInRace = currentSelections[r.KOD] ?? []
                        let available = r.atlar?.filter { h in h.KOSMAZ != true && !selectedInRace.contains(h.KOD) }
                            .sorted(by: { ($0.AGF1 ?? 0) > ($1.AGF1 ?? 0) }) ?? []
                        
                        if let nextHorse = available.first {
                            let count = Double(max(selectedInRace.count, 1))
                            let nextPrice = (currentCombos / count) * (count + 1) * unitPrice
                            if nextPrice <= maxBudget { validMoves.append((r.KOD, nextHorse.KOD, nextPrice)) }
                        }
                    }
                    
                    if let move = validMoves.randomElement() {
                        currentSelections[move.raceKod]?.insert(move.horseKod)
                        canImprove = true
                    }
                }
                
                let finalPrice = races.reduce(1.0) { $0 * Double(max(currentSelections[$1.KOD]?.count ?? 0, 1)) } * unitPrice
                if finalPrice > bestPriceFound {
                    bestPriceFound = finalPrice
                    bestSelections = currentSelections
                }
            }
            
            await MainActor.run {
                self.autoGeneratedHorses = bestSelections
                self.isLoadingData = false
                self.navigateToTicket = true
            }
        }
    }

    private func getGanyanTypes(for day: BetRaceDay?) -> [BetType] {
        guard let day = day else { return [] }
        let allowed = ["6'lı Ganyan", "5'li Ganyan", "4'lü Ganyan", "3'lü Ganyan"]
        return day.bahisler.filter { type in allowed.contains { type.BAHIS.localizedCaseInsensitiveContains($0) } }
    }
    
    private func betTypeLabelForAI(for type: BetType, list: [BetType]) -> String {
        let sameNameTypes = list.filter { $0.BAHIS == type.BAHIS }
        if sameNameTypes.count > 1 {
            let sortedByRace = sameNameTypes.sorted { ($0.kosular.first ?? 0) < ($1.kosular.first ?? 0) }
            if let index = sortedByRace.firstIndex(where: { $0.id == type.id }) { return "\(index + 1). \(type.BAHIS.uppercased())" }
        }
        return type.BAHIS.uppercased()
    }
    
    private func formattedRaceDayTitle(for day: BetRaceDay?) -> String {
        guard let day = day else { return "Seçiniz" }
        let yer = day.YER.uppercased()
        if let date = Self.dateFormatter.date(from: day.TARIH) {
            return "\(yer) (\(Self.dayFormatter.string(from: date).uppercased()))"
        }
        return yer
    }

    private func filteredRacesForAI(for raceDay: BetRaceDay, betType: BetType) -> [BetRace] {
        let startRaceNo = betType.kosular.first ?? 1
        let name = betType.BAHIS.lowercased()
        let legCountMap: [String: Int] = ["7'li": 7, "6'lı": 6, "5'li": 5, "4'lü": 4, "3'lü": 3]
        let legCount = legCountMap.first(where: { name.contains($0.key) })?.value ?? 1
        
        let sortedRaces = (raceDay.kosular ?? []).sorted { (Int($0.NO) ?? 0) < (Int($1.NO) ?? 0) }
        if let startIndex = sortedRaces.firstIndex(where: { Int($0.NO) == startRaceNo }) {
            return Array(sortedRaces[startIndex..<min(startIndex + legCount, sortedRaces.count)])
        }
        return []
    }
}

// MARK: - View Components
private extension TicketSetupView {
    
    struct LogoHeaderView: View {
        let themePrimary: Color
        private let logoSize: CGFloat = 100
        
        var body: some View {
            ZStack {
                Circle()
                    .fill(themePrimary.opacity(0.1))
                    .frame(width: logoSize, height: logoSize)
                Circle()
                    .stroke(LinearGradient(colors: [themePrimary, .clear], startPoint: .topLeading, endPoint: .bottomTrailing), lineWidth: 3)
                    .frame(width: logoSize + 10, height: logoSize + 10)
                Image("tayzekatransparent")
                    .resizable()
                    .scaledToFit()
                    .frame(width: logoSize + 60, height: logoSize + 60)
                    .clipShape(Circle())
            }
        }
    }
    
    struct MainOptionsView: View {
        let themePrimary: Color
        let prepareAISelection: () -> Void
        let createTicketManually: () -> Void
        
        var body: some View {
            VStack(spacing: 12) {
                optionButton(title: "TayZeka Hazırlasın", subtitle: "Bütçene göre en iyi analizi yap", icon: "sparkles", isPrimary: true, action: prepareAISelection)
                optionButton(title: "Kendim Oluşturacağım", subtitle: "Kuponu tamamen sen kontrol et", icon: "hand.tap.fill", isPrimary: false, action: createTicketManually)
            }
            .padding(.horizontal, 24)
        }
        
        private func optionButton(title: String, subtitle: String, icon: String, isPrimary: Bool, action: @escaping () -> Void) -> some View {
            Button(action: action) {
                HStack(spacing: 12) {
                    ZStack {
                        Circle().fill(.white.opacity(isPrimary ? 0.2 : 0.1)).frame(width: 40, height: 40)
                        Image(systemName: icon).font(.system(size: 16))
                    }
                    VStack(alignment: .leading, spacing: 1) {
                        Text(title).font(.system(size: 15, weight: .bold))
                        Text(subtitle).font(.system(size: 11)).opacity(isPrimary ? 0.8 : 1.0).foregroundColor(isPrimary ? .black : .secondary)
                    }
                    Spacer()
                    Image(systemName: "chevron.right").font(.system(size: 12, weight: .bold)).foregroundColor(isPrimary ? .black : .secondary)
                }
                .padding(.all, 16)
                .background(isPrimary ? LinearGradient(colors: [themePrimary, themePrimary.opacity(0.7)], startPoint: .leading, endPoint: .trailing) : LinearGradient(colors: [Color.white.opacity(0.05)], startPoint: .leading, endPoint: .trailing))
                .foregroundColor(isPrimary ? .black : .white)
                .cornerRadius(16)
                .overlay(RoundedRectangle(cornerRadius: 16).stroke(Color.white.opacity(isPrimary ? 0.0 : 0.1), lineWidth: 1))
            }
        }
    }
    
    struct AISettingsView: View {
        let raceDays: [BetRaceDay]
        @Binding var selectedDayIndex: Int
        @Binding var selectedBetIndex: Int
        @Binding var budget: String
        @FocusState.Binding var isBudgetFocused: Bool
        
        let themePrimary: Color
        let themeAccent: Color
        let quickBudgets: [String]
        
        let getGanyanTypes: (BetRaceDay?) -> [BetType]
        let betTypeLabelForAI: (BetType, [BetType]) -> String
        let formattedRaceDayTitle: (BetRaceDay?) -> String
        let onGenerate: () -> Void
        let onBack: () -> Void

        var body: some View {
            let currentDay = selectedDayIndex < raceDays.count ? raceDays[selectedDayIndex] : nil
            let available = getGanyanTypes(currentDay)
            let currentBet = selectedBetIndex < available.count ? available[selectedBetIndex] : nil

            VStack(spacing: 0) {
                Menu {
                    Picker("", selection: $selectedDayIndex) {
                        ForEach(0..<raceDays.count, id: \.self) { i in
                            Text(formattedRaceDayTitle(raceDays[i])).tag(i)
                        }
                    }
                } label: {
                    menuRow(
                        icon: "mappin.and.ellipse",
                        label: "HİPODROM",
                        value: formattedRaceDayTitle(currentDay),
                        accentColor: themePrimary
                    )
                }

                rowDivider

                // Bahis türü satırı
                Menu {
                    Picker("", selection: $selectedBetIndex) {
                        ForEach(0..<available.count, id: \.self) { i in
                            Text(betTypeLabelForAI(available[i], available)).tag(i)
                        }
                    }
                } label: {
                    menuRow(
                        icon: "ticket.fill",
                        label: "BAHİS TÜRÜ",
                        value: currentBet.map { betTypeLabelForAI($0, available) } ?? "Seçiniz",
                        accentColor: themePrimary
                    )
                }

                rowDivider

                VStack(alignment: .leading, spacing: 12) {
                    HStack(spacing: 6) {
                        Text("BÜTÇE")
                            .font(.system(size: 11, weight: .black))
                            .foregroundColor(themePrimary)
                    }

                    HStack(alignment: .firstTextBaseline, spacing: 4) {
                        Text("₺")
                            .font(.system(size: 28, weight: .bold))
                            .foregroundColor(themeAccent)
                        TextField("500", text: $budget)
                            .keyboardType(.decimalPad)
                            .font(.system(size: 28, weight: .heavy, design: .rounded))
                            .foregroundColor(themeAccent)
                            .focused($isBudgetFocused)
                    }

                    ScrollView(.horizontal, showsIndicators: false) {
                        HStack(spacing: 8) {
                            ForEach(quickBudgets, id: \.self) { amount in
                                Button {
                                    budget = amount
                                    isBudgetFocused = false
                                } label: {
                                    Text("\(amount)₺")
                                        .font(.system(size: 12, weight: .semibold))
                                        .padding(.horizontal, 10)
                                        .padding(.vertical, 7)
                                        .background(budget == amount ? themeAccent.opacity(0.2) : Color.white.opacity(0.06))
                                        .foregroundColor(budget == amount ? themeAccent : .white.opacity(0.5))
                                        .cornerRadius(20)
                                        .overlay(
                                            RoundedRectangle(cornerRadius: 20)
                                                .stroke(budget == amount ? themeAccent.opacity(0.7) : Color.clear, lineWidth: 1)
                                        )
                                }
                            }
                        }
                        .padding(.bottom, 2)
                    }
                }
                .padding(.horizontal, 18)
                .padding(.vertical, 16)

                rowDivider

                // Butonlar
                VStack(spacing: 10) {
                    Button(action: onGenerate) {
                        HStack(spacing: 8) {
                            Image(systemName: "sparkles")
                                .font(.system(size: 12, weight: .bold))
                            Text("HAZIRLA")
                                .font(.system(size: 12, weight: .heavy))
                                .tracking(1.5)
                        }
                        .foregroundColor(.black)
                        .frame(maxWidth: .infinity)
                        .padding(.vertical, 15)
                        .background(
                            LinearGradient(
                                colors: [themePrimary, themePrimary.opacity(0.75)],
                                startPoint: .leading,
                                endPoint: .trailing
                            )
                        )
                        .cornerRadius(14)
                        .shadow(color: themePrimary.opacity(0.45), radius: 14, x: 0, y: 5)
                    }
                    Button(action: onBack) {
                        Text("Vazgeç")
                            .font(.system(size: 13, weight: .medium))
                            .foregroundColor(.white.opacity(0.35))
                    }
                }
                .padding(.horizontal, 18)
                .padding(.vertical, 16)
            }
            .background(Color(white: 0.1))
            .cornerRadius(18)
            .overlay(
                RoundedRectangle(cornerRadius: 18)
                    .stroke(Color.white.opacity(0.08), lineWidth: 1)
            )
            .padding(.horizontal, 20)
        }

        private var rowDivider: some View {
            Rectangle()
                .fill(Color.white.opacity(0.07))
                .frame(height: 1)
                .padding(.horizontal, 14)
        }

        private func menuRow(icon: String, label: String, value: String, accentColor: Color) -> some View {
            HStack(spacing: 14) {
                Image(systemName: icon)
                    .font(.system(size: 15, weight: .semibold))
                    .foregroundColor(accentColor)
                    .frame(width: 22)

                VStack(alignment: .leading, spacing: 3) {
                    Text(label)
                        .font(.system(size: 10, weight: .black))
                        .foregroundColor(accentColor.opacity(0.8))
                    Text(value)
                        .font(.system(size: 15, weight: .bold))
                        .foregroundColor(.white)
                        .lineLimit(1)
                }

                Spacer()

                Image(systemName: "chevron.up.chevron.down")
                    .font(.system(size: 11, weight: .medium))
                    .foregroundColor(.white.opacity(0.25))
            }
            .padding(.horizontal, 18)
            .padding(.vertical, 15)
            .contentShape(Rectangle())
        }
    }
    
    struct ProcessingOverlay: View {
        let text: String
        let themePrimary: Color
        @State private var isAnimating = false
        
        var body: some View {
            ZStack {
                Color.black.opacity(0.85).ignoresSafeArea()
                VStack(spacing: 25) {
                    Circle()
                        .trim(from: 0, to: 0.7)
                        .stroke(themePrimary, lineWidth: 4)
                        .frame(width: 50, height: 50)
                        .rotationEffect(.degrees(isAnimating ? 360 : 0))
                    Text(text).font(.headline).foregroundColor(.white)
                }
            }
            .onAppear {
                withAnimation(.linear(duration: 1).repeatForever(autoreverses: false)) { isAnimating = true }
            }
        }
    }
}

