/*
import SwiftUI

struct TicketSetupView: View {

    // MARK: - State

    @State private var navigateToTicket = false
    @State private var showAISettings = false
    @State private var isLoadingData = false

    @State private var raceDays: [BetRaceDay] = []
    @State private var selectedDayIndex: Int = 0
    @State private var selectedBetIndex: Int = 0
    @State private var budget: String = "500"
    @State private var autoGeneratedHorses: [String: Set<String>]? = nil

    @FocusState private var isBudgetFocused: Bool

    // MARK: - Theme

    let themePrimary = Color.cyan
    let themeAccent = Color.orange
    let quickBudgets = ["100","250","500","1000","2500"]

    // MARK: - Body

    var body: some View {

        NavigationStack {

            ZStack {

                // Background
                RadialGradient(
                    colors: [Color(white: 0.15), .black],
                    center: .center,
                    startRadius: 2,
                    endRadius: 700
                )
                .ignoresSafeArea()

                VStack(spacing: 24) {

                    Spacer(minLength: 10)

                    LogoHeaderView(themePrimary: themePrimary)

                    if showAISettings {
                        AISettingsView(
                            budget: $budget,
                            isBudgetFocused: $isBudgetFocused,
                            themePrimary: themePrimary,
                            themeAccent: themeAccent,
                            quickBudgets: quickBudgets,
                            onGenerate: generateAIKupon,
                            onBack: {
                                dismissKeyboard()
                                withAnimation(.easeInOut) {
                                    showAISettings = false
                                }
                            }
                        )
                        .transition(.move(edge: .trailing).combined(with: .opacity))
                    } else {
                        MainOptionsView(
                            themePrimary: themePrimary,
                            prepareAISelection: {
                                withAnimation {
                                    showAISettings = true
                                }
                            },
                            createTicketManually: {
                                navigateToTicket = true
                            }
                        )
                    }

                    Spacer()
                }
                .padding(.horizontal, 24)
                .contentShape(Rectangle())
                .onTapGesture {
                    dismissKeyboard()
                }

                if isLoadingData {
                    ProcessingOverlay(text: "Analiz Ediliyor...", themePrimary: themePrimary)
                }
            }
            .navigationDestination(isPresented: $navigateToTicket) {
                Text("TicketView Buraya Gelecek")
            }
        }

        // 🔥 STABLE KEYBOARD BAR
        .safeAreaInset(edge: .bottom) {
            if isBudgetFocused {
                keyboardToolbar
            }
        }
    }

    // MARK: - Keyboard Toolbar

    private var keyboardToolbar: some View {
        HStack {
            Spacer()
            Button("Tamam") {
                dismissKeyboard()
            }
            .foregroundColor(themePrimary)
            .fontWeight(.bold)
            .padding(.horizontal)
        }
        .frame(height: 44)
        .background(.ultraThinMaterial)
    }

    private func dismissKeyboard() {
        isBudgetFocused = false
    }

    // MARK: - Dummy AI Generate

    private func generateAIKupon() {
        dismissKeyboard()
        isLoadingData = true

        DispatchQueue.main.asyncAfter(deadline: .now() + 1.5) {
            isLoadingData = false
            navigateToTicket = true
        }
    }
}

struct AISettingsView: View {

    @Binding var budget: String
    @FocusState.Binding var isBudgetFocused: Bool

    let themePrimary: Color
    let themeAccent: Color
    let quickBudgets: [String]

    let onGenerate: () -> Void
    let onBack: () -> Void

    var body: some View {

        VStack(spacing: 20) {

            VStack(alignment: .leading, spacing: 10) {

                Text("BÜTÇE")
                    .font(.caption)
                    .foregroundColor(themePrimary)

                HStack {
                    Image(systemName: "turkishlirasign")
                        .foregroundColor(themeAccent)

                    TextField("500", text: $budget)
                        .keyboardType(.numberPad)
                        .focused($isBudgetFocused)
                        .font(.title3.bold())
                        .foregroundColor(themeAccent)
                }
                .padding()
                .background(Color.black.opacity(0.3))
                .cornerRadius(12)

                ScrollView(.horizontal, showsIndicators: false) {
                    HStack {
                        ForEach(quickBudgets, id:\.self) { amount in
                            Button(amount + "₺") {
                                budget = amount
                                dismissKeyboard()
                            }
                            .padding(.horizontal,12)
                            .padding(.vertical,6)
                            .background(Color.white.opacity(0.1))
                            .cornerRadius(20)
                        }
                    }
                }
            }

            Button("HAZIRLA") {
                onGenerate()
            }
            .font(.headline.bold())
            .foregroundColor(.black)
            .frame(maxWidth: .infinity)
            .padding()
            .background(themePrimary)
            .cornerRadius(16)

            Button("Vazgeç") {
                onBack()
            }
            .foregroundColor(.gray)
        }
    }

    private func dismissKeyboard() {
        UIApplication.shared.sendAction(#selector(UIResponder.resignFirstResponder),
                                        to: nil,
                                        from: nil,
                                        for: nil)
    }
}

struct LogoHeaderView: View {

    let themePrimary: Color

    var body: some View {

        VStack(spacing: 14) {

            ZStack {
                Circle()
                    .fill(themePrimary.opacity(0.15))
                    .frame(width: 110, height: 110)
                    .blur(radius: 10)

                Circle()
                    .stroke(themePrimary.opacity(0.4), lineWidth: 2)
                    .frame(width: 100, height: 100)

                Image(systemName: "flag.checkered.2.crossed")
                    .font(.system(size: 42, weight: .bold))
                    .foregroundStyle(
                        LinearGradient(
                            colors: [themePrimary, .white],
                            startPoint: .topLeading,
                            endPoint: .bottomTrailing
                        )
                    )
            }

            VStack(spacing: 4) {
                Text("AI Kupon")
                    .font(.title.bold())
                    .foregroundColor(.white)

                Text("Akıllı yarış stratejini oluştur")
                    .font(.footnote)
                    .foregroundColor(.gray)
            }
        }
        .padding(.top, 10)
    }
}

struct MainOptionsView: View {

    let themePrimary: Color
    let prepareAISelection: () -> Void
    let createTicketManually: () -> Void

    var body: some View {

        VStack(spacing: 20) {

            OptionCard(
                title: "AI Kupon Hazırla",
                subtitle: "Bütçene göre otomatik akıllı seçim",
                icon: "brain.head.profile",
                themePrimary: themePrimary,
                action: prepareAISelection
            )

            OptionCard(
                title: "Manuel Kupon Oluştur",
                subtitle: "Atlarını kendin seç",
                icon: "hand.tap",
                themePrimary: themePrimary,
                action: createTicketManually
            )
        }
    }
}

struct OptionCard: View {

    let title: String
    let subtitle: String
    let icon: String
    let themePrimary: Color
    let action: () -> Void

    @State private var isPressed = false

    var body: some View {

        Button {
            action()
        } label: {

            HStack(spacing: 16) {

                ZStack {
                    Circle()
                        .fill(themePrimary.opacity(0.15))
                        .frame(width: 60, height: 60)

                    Image(systemName: icon)
                        .font(.system(size: 26, weight: .bold))
                        .foregroundColor(themePrimary)
                }

                VStack(alignment: .leading, spacing: 6) {
                    Text(title)
                        .font(.headline)
                        .foregroundColor(.white)

                    Text(subtitle)
                        .font(.caption)
                        .foregroundColor(.gray)
                }

                Spacer()

                Image(systemName: "chevron.right")
                    .foregroundColor(.gray)
            }
            .padding()
            .background(
                RoundedRectangle(cornerRadius: 20)
                    .fill(Color.white.opacity(0.05))
            )
            .overlay(
                RoundedRectangle(cornerRadius: 20)
                    .stroke(themePrimary.opacity(0.2), lineWidth: 1)
            )
            .scaleEffect(isPressed ? 0.97 : 1.0)
            .animation(.easeInOut(duration: 0.15), value: isPressed)
        }
        .buttonStyle(.plain)
        .pressEffect($isPressed)
    }
}

struct PressEffect: ViewModifier {

    @Binding var isPressed: Bool

    func body(content: Content) -> some View {
        content
            .gesture(
                DragGesture(minimumDistance: 0)
                    .onChanged { _ in
                        isPressed = true
                    }
                    .onEnded { _ in
                        isPressed = false
                    }
            )
    }
}

extension View {
    func pressEffect(_ isPressed: Binding<Bool>) -> some View {
        self.modifier(PressEffect(isPressed: isPressed))
    }
}

struct ProcessingOverlay: View {

    let text: String
    let themePrimary: Color

    @State private var animate = false

    var body: some View {

        ZStack {

            // Blur + karartma
            Color.black.opacity(0.6)
                .ignoresSafeArea()

            VStack(spacing: 24) {

                ZStack {

                    Circle()
                        .stroke(themePrimary.opacity(0.2), lineWidth: 8)
                        .frame(width: 110, height: 110)

                    Circle()
                        .trim(from: 0, to: 0.7)
                        .stroke(
                            AngularGradient(
                                gradient: Gradient(colors: [themePrimary, .white, themePrimary]),
                                center: .center
                            ),
                            style: StrokeStyle(lineWidth: 8, lineCap: .round)
                        )
                        .frame(width: 110, height: 110)
                        .rotationEffect(.degrees(animate ? 360 : 0))
                        .animation(
                            .linear(duration: 1)
                            .repeatForever(autoreverses: false),
                            value: animate
                        )

                    Image(systemName: "brain.head.profile")
                        .font(.system(size: 34, weight: .bold))
                        .foregroundColor(themePrimary)
                }

                Text(text)
                    .font(.headline)
                    .foregroundColor(.white)
            }
            .padding(40)
            .background(
                RoundedRectangle(cornerRadius: 28)
                    .fill(Color(white: 0.1))
                    .overlay(
                        RoundedRectangle(cornerRadius: 28)
                            .stroke(themePrimary.opacity(0.3), lineWidth: 1)
                    )
            )
            .shadow(color: themePrimary.opacity(0.4), radius: 20)
        }
        .onAppear {
            animate = true
        }
    }
}

#Preview() {
    TicketSetupView()
        .preferredColorScheme(.dark)
}
*/
